./lab1/cmake-build-debug/Comp_geom ./lab1/cmake-build-debug/x.pnm ./lab1/cmake-build-debug/x0.pnm 0
./lab1/cmake-build-debug/Comp_geom ./lab1/cmake-build-debug/a.pnm ./lab1/cmake-build-debug/a0.pnm 0
./lab1/cmake-build-debug/Comp_geom ./lab1/cmake-build-debug/x.pnm ./lab1/cmake-build-debug/x1.pnm 1
./lab1/cmake-build-debug/Comp_geom ./lab1/cmake-build-debug/a.pnm ./lab1/cmake-build-debug/a1.pnm 1
./lab1/cmake-build-debug/Comp_geom ./lab1/cmake-build-debug/x.pnm ./lab1/cmake-build-debug/x2.pnm 2
./lab1/cmake-build-debug/Comp_geom ./lab1/cmake-build-debug/a.pnm ./lab1/cmake-build-debug/a2.pnm 2
./lab1/cmake-build-debug/Comp_geom ./lab1/cmake-build-debug/x.pnm ./lab1/cmake-build-debug/x3.pnm 3
./lab1/cmake-build-debug/Comp_geom ./lab1/cmake-build-debug/a.pnm ./lab1/cmake-build-debug/a3.pnm 3
./lab1/cmake-build-debug/Comp_geom ./lab1/cmake-build-debug/x.pnm ./lab1/cmake-build-debug/x4.pnm 4
./lab1/cmake-build-debug/Comp_geom ./lab1/cmake-build-debug/a.pnm ./lab1/cmake-build-debug/a4.pnm 4
